-- Generated by scripts/build.ts from content/: edit the Markdown, not this file.
local _, ns = ...
ns.content = {
  chapters = {
    { id = "dun-morogh", title = "Dun Morogh", summary = "The snowbound valleys around Ironforge, cradle of the Bronzebeard clan.", entries = { "kharanos", "magni-bronzebeard", "war-of-the-three-hammers" } },
  },
  entries = {
    ["kharanos"] = {
      title = "Kharanos", kind = "place", chapter = "dun-morogh",
      unlock = { { area = 131 } },
      also = { "war-of-the-three-hammers" },
      text = {
        { "Kharanos sits in the cold heart of Dun Morogh, on the road between the training grounds of Coldridge Valley and the gates of Ironforge. It is a small town by dwarven reckoning: a smithy, a few stout houses, and the building that makes it famous, the Thunderbrew Distillery, where the Thunderbrew family has been perfecting its ales for longer than anyone cares to admit." },
        { "Do not mistake the warm hearth for safety. Frostmane trolls hold the hills to the west, troggs keep crawling up from the deep places, and since the fall of Gnomeregan its exiles share these roads with us. The town keeps its doors open all the same: a dwarf who turns away a cold traveller is no dwarf at all." },
      },
    },
    ["magni-bronzebeard"] = {
      title = "King Magni Bronzebeard", kind = "figure", chapter = "dun-morogh",
      unlock = { { npc = 2784 } },
      also = { "war-of-the-three-hammers" },
      text = {
        { "Magni Bronzebeard rules Ironforge from the High Seat, as the Bronzebeards have since the War of the Three Hammers. He is the eldest of three brothers, and the one who stayed. Muradin, the middle brother, went north with the prince of Lordaeron during the Third War and has not been heard from since. Brann, the youngest, would rather crawl through a titan ruin than sit through a council, and is the League's most famous explorer as well as its most often missing." },
        { "The king follows our work closely. If the stones of Uldaman tell the truth, the dwarves were not born of the mountain by chance but shaped from it, long ago, by the Titans themselves. It is a question that matters to him more than he admits." },
        { "His newest grief is his daughter. Princess Moira is held in the Dark Iron city beneath Blackrock Mountain, wed to Emperor Dagran Thaurissan. Ironforge calls it an abduction, and the king has promised a hero's reward to whoever brings her home." },
      },
    },
    ["war-of-the-three-hammers"] = {
      title = "The War of the Three Hammers", kind = "history", chapter = "dun-morogh",
      unlock = { { area = 77 } },
      also = { "magni-bronzebeard", "kharanos" },
      text = {
        { "Some two and a half centuries ago, Ironforge belonged to three clans at once. The Bronzebeards, the Wildhammers and the Dark Irons lived under a single High King, Modimus Anvilmar, and when he died they could not agree on who should follow him." },
        { "The quarrel became a war under the mountain. The Bronzebeards held the city. The Wildhammers, under Thane Khardros, were driven out and raised their own fortress at Grim Batol, and the Dark Irons of Sorcerer-Thane Thaurissan withdrew to the mountains of the south." },
        { "The Dark Irons were not finished. They marched on Ironforge and Grim Batol at once, and lost both battles. In his fury Thaurissan reached for a power far older than any clan and woke Ragnaros, the Lord of Fire. The south burned: the Searing Gorge and the Burning Steppes are what remained, and the Dark Irons have served the Firelord in Blackrock Mountain ever since." },
        { "The Wildhammers did not stay in Grim Batol either. The death of Queen Modgud, slain at its gates, left a darkness in the stone, and they made a new home at Aerie Peak in the Hinterlands. Ironforge still remembers which clan stayed." },
      },
    },
    ["foreword"] = {
      title = "A Word from the Archivist", kind = "note", chapter = "",
      unlock = { { always = true } },
      also = {  },
      text = {
        { "Traveller, if this ledger has found its way into your pack, then the Hall of Explorers has judged you worth the ink." },
        { "The League records everything: the stones our ancestors cut, the names of the clans, the wars that broke them and the roads that bound them together again. Most of it sleeps in the vaults beneath Ironforge, where no one reads it. Better that it should travel." },
        { "Wherever history was made, I have left a page for you. Read them by the fire, and remember that every ruin was once someone's home." },
        { italic = true, "An archivist of the Explorers' League, Hall of Explorers, Ironforge" },
      },
    },
  },
  -- English names of the areas used above (when the client can't name an area id).
  areaNames = { [77] = "Anvilmar", [131] = "Kharanos" },
}
